# Generated by Django 5.2.5 on 2025-08-11 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("municipios", "0001_initial"),
        ("unidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paroquia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(db_index=True, max_length=255)),
                ("bairro", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="municipios.cidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unidades.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paróquia",
                "verbose_name_plural": "Paróquias",
                "db_table": "paroquias",
            },
        ),
    ]
