# Generated by Django 5.2.5 on 2025-08-11 23:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(db_index=True, max_length=255)),
                (
                    "digito",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("vencimento", models.PositiveIntegerField(default=40)),
                ("bloqueado", models.BooleanField(default=False)),
                (
                    "tipo",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Root"),
                            (1, "Nacional"),
                            (2, "Regional"),
                            (3, "Diocesano"),
                            (4, "Setorial"),
                            (5, "Paróquia"),
                        ]
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="unidades.unidade",
                    ),
                ),
            ],
            options={
                "db_table": "unidades",
            },
        ),
        migrations.CreateModel(
            name="UserUnidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unidades.unidade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_unidade",
            },
        ),
        migrations.AddField(
            model_name="unidade",
            name="users",
            field=models.ManyToManyField(
                related_name="unidades",
                through="unidades.UserUnidade",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
