# Generated by Django 5.2.5 on 2025-08-11 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("materiais", "0001_initial"),
        ("municipios", "0001_initial"),
        ("unidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.PositiveSmallIntegerField(db_index=True)),
                ("solicitante", models.CharField(db_index=True, max_length=255)),
                ("endereco", models.CharField(blank=True, max_length=255, null=True)),
                ("cep", models.CharField(blank=True, max_length=20, null=True)),
                ("telefones", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "codigo_correios",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("obs", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="municipios.cidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unidades.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "db_table": "pedidos",
            },
        ),
        migrations.CreateModel(
            name="PedidoMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "valor_venda",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materiais.material",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pedidos.pedido"
                    ),
                ),
            ],
            options={
                "db_table": "pedido_material",
                "unique_together": {("pedido", "material")},
            },
        ),
        migrations.AddField(
            model_name="pedido",
            name="materiais",
            field=models.ManyToManyField(
                related_name="pedidos",
                through="pedidos.PedidoMaterial",
                to="materiais.material",
            ),
        ),
    ]
