# Generated by Django 5.2.5 on 2025-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Novo"),
                    (1, "Recebido"),
                    (2, "Realizado"),
                    (3, "Cancelado"),
                ],
                db_index=True,
                default=0,
            ),
        ),
    ]
