# Generated by Django 5.2.5 on 2025-08-11 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("unidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DadoBancario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(blank=True, max_length=255, null=True)),
                ("agencia", models.CharField(blank=True, max_length=255, null=True)),
                ("conta", models.CharField(blank=True, max_length=255, null=True)),
                ("pix", models.CharField(blank=True, max_length=255, null=True)),
                ("cnpj", models.CharField(blank=True, max_length=18, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unidades.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dado Bancário",
                "verbose_name_plural": "Dados Bancários",
                "db_table": "dado_bancarios",
            },
        ),
    ]
