# Generated by Django 5.2.5 on 2025-08-11 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("paroquias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Casal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ele", models.CharField(db_index=True, max_length=255)),
                ("ela", models.CharField(db_index=True, max_length=255)),
                (
                    "email_ele",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "email_ela",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "telefone_ele",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True
                    ),
                ),
                (
                    "telefone_ela",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True
                    ),
                ),
                ("obs", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paroquia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="paroquias.paroquia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Casal",
                "verbose_name_plural": "Casais",
                "db_table": "casals",
            },
        ),
    ]
