# Generated by Django 5.2.5 on 2025-12-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casais", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casal",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="casais/"),
        ),
    ]
