# Generated by Django 5.2.5 on 2025-08-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_noticia_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="imagem_principal",
            field=models.ImageField(
                blank=True,
                help_text="Imagem que será exibida como destaque da notícia",
                null=True,
                upload_to="noticias/imagens/",
                verbose_name="Imagem Principal",
            ),
        ),
    ]
