# Generated by Django 5.2.5 on 2025-08-13 16:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_noticia_imagem_principal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="imagem_principal",
            field=models.ImageField(
                blank=True,
                help_text="Imagem que será exibida como destaque da notícia",
                null=True,
                upload_to=blog.models.noticia_image_upload_path,
                verbose_name="Imagem Principal",
            ),
        ),
    ]
