# Generated by Django 5.2.5 on 2026-04-06 22:08

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_noticia_imagem_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=10, verbose_name='Ano')),
                ('imagem', models.ImageField(upload_to=blog.models.estatistica_imagem_upload_path, verbose_name='Imagem de Capa')),
                ('arquivo', models.FileField(upload_to=blog.models.estatistica_arquivo_upload_path, verbose_name='Arquivo (PDF)')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Regional')),
                ('regional_id', models.CharField(choices=[('noroeste', 'Noroeste'), ('norte1', 'Norte 1'), ('norte2', 'Norte 2'), ('norte3', 'Norte 3'), ('nordeste1', 'Nordeste 1'), ('nordeste2', 'Nordeste 2'), ('nordeste3', 'Nordeste 3'), ('nordeste4', 'Nordeste 4'), ('nordeste5', 'Nordeste 5'), ('centroOeste', 'Centro-Oeste'), ('oeste1', 'Oeste 1'), ('oeste2', 'Oeste 2'), ('leste1', 'Leste 1'), ('leste2', 'Leste 2'), ('leste3', 'Leste 3'), ('sul1', 'Sul 1'), ('sul2', 'Sul 2'), ('sul3', 'Sul 3'), ('sul4', 'Sul 4')], max_length=50, unique=True, verbose_name='ID da Regional')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('casal', models.CharField(blank=True, max_length=200, verbose_name='Casal Responsável')),
                ('padre', models.CharField(blank=True, max_length=200, verbose_name='Padre / Assistente')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=blog.models.regional_imagem_upload_path, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Regional',
                'verbose_name_plural': 'Regionais',
                'ordering': ['nome'],
            },
        ),
    ]
