# Generated by Django 5.2.5 on 2026-06-15 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_add_estatistica_regional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('regiao', models.CharField(blank=True, max_length=200, verbose_name='Região')),
                ('perfil', models.CharField(choices=[('editor', 'Editor'), ('revisor', 'Revisor')], default='editor', max_length=10, verbose_name='Perfil de Acesso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Colaborador de Notícias',
                'verbose_name_plural': 'Colaboradores de Notícias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='blog.colaboradornoticia', verbose_name='Autor (Colaborador)'),
        ),
        migrations.CreateModel(
            name='TokenAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='blog.colaboradornoticia', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Token de Acesso',
                'verbose_name_plural': 'Tokens de Acesso',
                'ordering': ['-criado_em'],
            },
        ),
    ]
