# Generated by Django 5.2.5 on 2026-06-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_colaboradornoticia_noticia_autor_tokenacesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regional',
            name='regional_id',
            field=models.CharField(choices=[('noroeste', 'Noroeste'), ('norte1', 'Norte 1'), ('norte2', 'Norte 2'), ('norte3', 'Norte 3'), ('nordeste1', 'Nordeste 1'), ('nordeste2', 'Nordeste 2'), ('nordeste3', 'Nordeste 3'), ('nordeste4', 'Nordeste 4'), ('nordeste5', 'Nordeste 5'), ('centroOeste', 'Centro-Oeste'), ('oeste1', 'Oeste 1'), ('oeste2', 'Oeste 2'), ('leste1', 'Leste 1'), ('leste2', 'Leste 2'), ('leste3', 'Leste 3'), ('sul1', 'Sul 1'), ('sul2', 'Sul 2'), ('sul3', 'Sul 3'), ('sul4', 'Sul 4'), ('canada', 'Canadá')], max_length=50, unique=True, verbose_name='ID da Regional'),
        ),
    ]
