# Generated by Django 5.2.5 on 2025-08-11 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("casais", "0001_initial"),
        ("equipes", "0001_initial"),
        ("paroquias", "0001_initial"),
        ("unidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CasalEncontro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "casal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="casais.casal"
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="equipes.equipe",
                    ),
                ),
            ],
            options={
                "db_table": "casal_encontro",
            },
        ),
        migrations.CreateModel(
            name="Encontro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="S/N",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("etapa", models.PositiveSmallIntegerField()),
                ("data", models.DateField()),
                ("quadrante", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "casais",
                    models.ManyToManyField(
                        related_name="encontros",
                        through="encontros.CasalEncontro",
                        to="casais.casal",
                    ),
                ),
                (
                    "paroquia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="paroquias.paroquia",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unidades.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encontro",
                "verbose_name_plural": "Encontros",
                "db_table": "encontros",
            },
        ),
        migrations.AddField(
            model_name="casalencontro",
            name="encontro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="encontros.encontro"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="casalencontro",
            unique_together={("casal", "encontro")},
        ),
    ]
